### ISSUE TITLE
sign all plugins and products

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.designer#135]
it would be good if we can get all our plugins (and new product) signed, so one avoids the warnings when one installs/updates.

Is it as simple as presented here?
https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_Jar.2Fplugins.2FWindows_exe.2FmacOS_App_files.3F

**Comment by berezovskyi** [comment]
Wow, that actually seems really easy!

**Comment by jadelkhoury** [comment]
Yes, but I saw some stackoverflow entries about some configurations we might have to do.
Main question is how can we test it locally. Or do we have to do trial/error on Jenkins server?

**Comment by berezovskyi** [comment]
Just created https://ci.eclipse.org/lyo/view/1Enabled/job/sign-dmg-product/

Unfortunately, the signed app does not work on my macOS. Before:

![image](https://user-images.githubusercontent.com/64734/72551768-d26f1800-3895-11ea-88c1-b7191a67549d.png)

So, I can't open it. But after signing, I get this:

![image](https://user-images.githubusercontent.com/64734/72552580-760cf800-3897-11ea-8630-b49911a91b52.png)

Apparently, signing is not notarization https://www.eclipse.org/lists/platform-dev/msg01793.html so we might have to wait before we can use the service. For now, I am unable to run the product due to the company settings on signing 😞 

You can try to modify the build config to sign a Windows executable and see how it goes.

**Comment by berezovskyi** [comment]
The signing seems to be done correctly:

```
$ codesign --verify Eclipse\ signed\ no2.app --verbose
Eclipse signed no2.app: valid on disk
Eclipse signed no2.app: satisfies its Designated Requirement
```

**Comment by jadelkhoury** [comment]
Can we sign the product, before we first sign the jar files? Even if possible, I'd rather get it working on the jars/plugins first. 
And, it doesn't seem that you are using maven to do the signing?

**Comment by berezovskyi** [comment]
The big problem is that mac does not run unsigned executables. Signing JARs is the second most important thing. I will have to check the maven process, as maven installs the JARs into the repo after compiling.

--
/Andrew
(from phone)

On 16 Jan 2020, at 22:57, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we sign the product, before we first sign the jar files? Even if possible, I'd rather get it working on the jars/plugins first.
And, it doesn't seem that you are using maven to do the signing?
