### ISSUE TITLE
Ambiguous methods created for the Creation Factory in the Mgr class

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#24]
The following model 

![image](https://user-images.githubusercontent.com/64734/44805620-06746b00-abc5-11e8-8de1-c2da515dac30.png)

leads to the generation of the following code:

![image](https://user-images.githubusercontent.com/64734/44805636-12602d00-abc5-11e8-84d1-730fc75aecaa.png)

I have no simple workaround for this 🤔

**Comment by berezovskyi** [comment]
@jadelkhoury you were asking to separate the "good to fix" from "need to fix" bugs. I have added the label "blocker" to this bug to indicate it needs to be fixed. Will that do?

**Comment by jadelkhoury** [comment]
>@jadelkhoury you were asking to separate "good to fix" from "need to fix" bugs. I have added the label >"blocker" to this bug to indicate it needs to be fixed. Will that do?

It's one component that helps. But We need to have a process in place for your project.

**Comment by jadelkhoury** [comment]
@berezovskyi The generator is not fool-proof and that's an issue I am aware of. 
The generator does (stupidly) follow the model and produce a method for each such CreationFactory in the model. 
One reason to have multiple CreationFactories for the same resource PlanExecutionRequest is because one has different parameters for such creations. If that is hte cause, different method signatures will be produced.
But in your case, it seems that you have the same signiture. So what is the purpose of multiple creationFactories for the same resource?
Can you possible just have one? Maybe that CF is separate/independant from the other services and/or ServiceProviders?

**Comment by jadelkhoury** [comment]
I guess a more robust generation would produce a single method for all these CF capabilities.
But I don't think that would help with your String paramter beltId, so it seems to be that you somehow want different methods for these differnet CFs?

**Comment by jadelkhoury** [comment]
and here's a workaround for the time being.

Set the "Creation URI" of the 3 CreationFactories to be the following (in some random choice)
* create
* create/{aaa}
* create/{aaa}/{bbb}

Generate and note that each creation method in the manager will have a different signature now 👍

**Comment by berezovskyi** [comment]
I need a kind of an SP as a parameter in addition to the SP id. I expected different methods :)

Eg there is a “Robot” SP and a “Shelf” SP the creation factory would save/process the resource differently for robot with id 1 from a shelf service with id 1.

I can surely add kind and id properties to the resource being created and treat them internally as an SP kind and an SP id, but that would be a hack. Plus the generated code fails to compile out of the box :)

–Andrew.
(sent from my phone)

**Comment by berezovskyi** [comment]
Oh, sorry, didn’t see the last answer. Perfect, thanks, will try tomorrow!

–Andrew.
(sent from my phone)

**Comment by berezovskyi** [comment]
Thanks @jadelkhoury, the signatures indeed do not clash any more. But then, I have to insert some random strings for those path parameters...

How hard would it be to apply a correct fix? I have traced the name of the creation factory method in the adaptor manager class to the following query:

    creationMethodName(aCreationFactory: CreationFactory)

In other queries, there are already calls to `aCreationFactory.eContainer(Service)` and I think we can get the SP the same way, e.g.

    aCreationFactory.eContainer(Service).eContainer(ServiceProvider)

Actually, there is a query `containingServiceProvider`, which does the same. _Why do we need to call `oclAsType` method, by the way?_

I was not able to find the query that would return the SP namespace, but the closest I got was this:

    aService.containingServiceProvider().instanceURI()

Jad, what do you think?

**Comment by jadelkhoury** [comment]
I am not sure how accessing the containing ServiceProvider be of help here. 

If I am to take your example above, my suggestion is to add some intelligence to the generator so that the 1st and 3rd methods (which are exactly the same) are only generated once. 
Note that this does not solve the problem completly since the 2nd method still has the same Java method signature. But in that case, I think there is something fundamentally wrong with the model that the generator should not hide? (unless I misunderstood it).

That is, the generator avoids the duplication of methods if they have exactly the same set of parameter names, as well as return type. 
This is NOT the same as having the same Java signature (where only number and types of paramters matter).

**Comment by jadelkhoury** [comment]
But if it can be motivated that the 2nd method is indeed different from the 1st/3rd method, then we need to find another solution.

**Comment by jadelkhoury** [comment]
Alternative (ugly?) solution:
if there are more than 1 CF for a particular resource type, we name each method "createPlanExecutionRequestForCreationFactory1". Where "CreationFactory1" is actually the name of hte CreationFactory. So in your case, you will need to give the factories different names yourself.

What I like with this approach is that the method names are quite clean and unchanged from current behavioru for 99% of the cases where there is only 1 CF per method.
