### ISSUE TITLE
Vocabulary constants are not imported properly

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#96]
The following import was missing from the generated code in `XyzResource` and `IXyzResource` classes:

    import org.eclipse.lyo.oslc.domains.Oslc_rmVocabularyConstants;

**Comment by jadelkhoury** [comment]
Is there a chance you can share a link to a project so I can reproduce?

**Comment by jadelkhoury** [comment]
I won't even try to argue that this is not confusing. I would really love to find a solution that is more intuitive. But here comes an explanation as to why "this is not a bug. It's a feature" :-)

I'm guessing that XyzResource and the RM specs are modelled in two separate Lyo models (M1 & M2 respectively). 
The generator works on each model separately. Just because M1 includes M2, we do not generate what belongs M2. (Because M2 might itself need to be generated independtly)
The idea is that if model M1 refers to M2. Then the respective maven project P1 should include a dependency on P2.

That is, for your particular case, are you sure you are not missing a maven dependency to the RM project under lyo.domains?

What can we do about this confusion?

**Comment by berezovskyi** [comment]
@jadelkhoury nop, same domain.

here you go: https://github.com/eclipse/lyo.domains/pull/12/files#diff-9cb816daf0dbdfc4ed907e7bfed54236R72

**Comment by berezovskyi** [comment]
would be good to fix :)

**Comment by jadelkhoury** [comment]
Yes, so I can confirm we have a bug. 
But unfortunately it is a mess to fix. I'd like to give it some time so I can do it properly once and for all.
The problem in short: I create a class for constants for each DomainSpec (where the shapes are created). But if the resources are explicitly described by a Vocab, I also create a class for that Vocab. 

I think the best approach is to no longer produce these DS classes. Only Vocab classes.
